export default {
	ADD_KEY_PRESSED: "ADD_KEY_PRESSED",
	RESET_KEY_PRESSED: "RESET_KEY_PRESSED",
	MINUS_KEY_PRESSED: "MINUS_KEY_PRESSED",
	NUMBER_KEY_PRESSED: "NUMBER_KEY_PRESSED",
	DELETE_KEY_PRESSED: "DELETE_KEY_PRESSED",
	DIVISION_KEY_PRESSED: "DIVISION_KEY_PRESSED",
	MULTIPLICATION_KEY_PRESSED: "MULTIPLICATION_KEY_PRESSED",
};
